Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

Задание 3
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

Задание 4
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

Задание 5
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [2]:
# вариант 1
x = np.arange(9,-1,-1)
x

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [3]:
# вариант 2
x = np.arange( 0, 10)[::-1]
x

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [4]:
n = int(input('Введите N: '))
mtx = np.diag(np.arange(n,-1,-1))
mtx.diagonal().sum()


Введите N: 10


55

Задание 3.
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [5]:
import pandas as pd

In [6]:
# https://grouplens.org/datasets/movielens/

df = pd.read_csv('ratings.csv')
df.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [30]:
filtered_5 = df[df['rating']==5.0].groupby('movieId').count().sort_values('userId', ascending=False).reset_index()
filtered_5.head(1)

movieId  userId  rating  timestamp
0      318     153     153        153

Задание 4. По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [32]:
df = pd.read_csv('power.csv')

In [104]:
df.head()

country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [105]:
df[(df['year']>=2005) & (df['year']<2010) & (df['category'].isin([4,12,21])) &(df['country'].isin(['Estonia', 'Latvia', 'Lithuania']))].quantity.sum()

201650.0

Задание 5. Решите систему уравнений: 
4x + 2y + z = 4
x + 3y = 12 
5y + 4z = -3

In [109]:
# коэффициенты при переменных в левой части уравнения
a = np.array( [ [4, 2, 1], [1, 3, 0] , [0, 5, 4]] )

# значения в правой части уравнения
b = np.array( [4, 12, -3] )

from numpy import linalg

linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [110]:
# проверка верности

np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

Ура :)