Лабораторная работа по модулю “Python для анализа данных”
Списки и строки – одни из важных начальных понятий для любого дата сайентиста, поскольку на знании принципов
работы с ними строится работа с препроцессингом и обработкой данных в python в целом и работы с модулем pandas в
частности:
1. Дан произвольный список, содержащий только числа. Выведите результат сложения всех чисел больше 10.
2. Пусть задан список, содержащий строки. Выведите все строки, заканчивающиеся буквой r.
3. Сгенерируйте и выведите cлучайную строку размером 6 символов, содержащую только цифры. Строка должна
содержать хотя бы одну цифру 3.
4. Пусть дана строка произвольной длины. Выведите информацию о том, сколько в ней символов и сколько слов.
Матрицы-следующее за списками и строками важное понятие. Широко используется в линейной алгебре. Находит свое
применение в современных рекомендательных системах и архитектуре нейронных сетей:
1. Пусть дана матрица чисел размером NхN. Представьте данную матрицу в виде списка. Выведите результат сложения
всех элементов матрицы.
2. Пусть дана матрица чисел размером NхM. Найти столбец матрицы с максимальной суммой элементов.
Работа с динамичными структурами важная часть в имплементации вашего кода в продакшн систему:
1. Пусть список студентов представлен в виде структуры [[No, ФИО, Возраст,Группа],[No, ФИО, Возраст, Группа],[No, ФИО,
Возраст, Группа]]. Преобразуйте список в словарь вида: {No: [ФИО, Возраст, Группа], No:[....], No: [....]}
2. Добавьте к задаче No6 для словаря возможность (без преобразования словаря обратно в список) изменить группу
студента. Поиск по «ФИО» («ФИО» студента и новый номер группы необходимо ввести с клавиатуры).
3. Добавьте к задаче No6 для словаря возможность (без преобразования словаря обратно в список) изменить возраст
студента. 

1.Дан произвольный список, содержащий только числа. Выведите результат сложения всех чисел больше 10.

In [78]:
import numpy as np

In [79]:
#произвольный список
lst = np.random.randint(1, 20, 20)
lst

array([ 8, 13,  3,  3, 13,  2, 16,  3,  3, 14, 12, 13,  9, 18,  6,  3,  7,
        2, 17, 14])

In [80]:
#сумма чисел больше 10
sum([num for num in lst if num>10])

130

2. Пусть задан список, содержащий строки. Выведите все строки, заканчивающиеся буквой r.

In [24]:
strs = ['Only two things we will regret on deathbed – that we are a little loved and little traveled.',
'Life is far too important a thing ever to talk seriously about. -r',
'In the middle of difficulty lies opportunity.']

In [81]:
for string in strs:
    if string[-1] == 'r':
        print(string)

Life is far too important a thing ever to talk seriously about. -r


In [95]:
import string

3. Сгенерируйте и выведите cлучайную строку размером 6 символов, содержащую только цифры. Строка должна содержать хотя бы одну цифру 3

In [145]:
rand_list = [np.random.choice(10) for i in range(6)]

In [146]:
rand_list

[0, 1, 2, 9, 2, 6]

In [158]:
rand_string = ''.join([str(num) for num in rand_list])


for char in rand_string[0:1]:
    first_letter = char

#если нет 3 в строке, заменим сделаем замену первой цифры на 3
if '3' not in rand_string:
    rand_string = rand_string.replace(first_letter, '3')

print(rand_string)

312926


4.Пусть дана строка произвольной длины. Выведите информацию о том, сколько в ней символов и сколько слов. 

In [114]:
queries = 'Only two things we will regret on deathbed – that we are a little loved and little traveled.'

num_word = 0

#подсчет слов
for word in queries.split(' '):
    num_word+=1

print(f'{num_word} слов')
print(f'{len(queries)} символов')

18 слов
92 символов


Матрицы-следующее за списками и строками важное понятие. Широко используется в линейной алгебре. Находит свое применение в современных рекомендательных системах и архитектуре нейронных сетей:

5. Пусть дана матрица чисел размером NхN. Представьте данную матрицу в виде списка. Выведите результат сложения всех элементов матрицы.

In [159]:
import numpy as np

In [176]:
x = np.arange(0,9,1)
x = x.reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [178]:
#матрица в видеп списка
x.tolist()

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [180]:
#сумма элементов матрицы
x.sum()

36

6. Пусть дана матрица чисел размером NхM. Найти столбец матрицы с максимальной суммой элементов.

In [184]:
x = np.arange(0,15,1)
x = x.reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [200]:
max_sum = 0
num_col = 0

for col in x:
    if col.sum() > max_sum:
        max_sum = col.sum()
        col_max_sum = num_col
        num_col +=1

print(f'столбец {col_max_sum} с максимальной суммой {max_sum}')

столбец 2 с максимальной суммой 60


Работа с динамичными структурами важная часть в имплементации вашего кода в продакшн систему:

7. Пусть список студентов представлен в виде структуры [[No, ФИО, Возраст,Группа],[No, ФИО, Возраст, Группа],[No, ФИО, Возраст, Группа]]. Преобразуйте список в словарь вида: {No: [ФИО, Возраст, Группа], No:[....], No: [....]}

In [251]:
lst = [[1, 'Иванов Иван', 18, 'A'],[2,'Петров Петр',17,'B'],[3, 'Сидоров Андрей',18, 'A']]

In [253]:
mydict = {student[0]:student[1:4] for student in lst}
mydict

{1: ['Иванов Иван', 18, 'A'],
 2: ['Петров Петр', 17, 'B'],
 3: ['Сидоров Андрей', 18, 'A']}

Добавьте к задаче No7 для словаря возможность (без преобразования словаря обратно в список) изменить группу студента. Поиск по «ФИО» («ФИО» студента и новый номер группы необходимо ввести с клавиатуры).

In [263]:
FIO = input('Введите ФИО: ')
new_group = input('Введите новую группу: ')

Введите ФИО: Петров Петр
Введите новую группу: C


In [279]:
for student in mydict.values():
    if student[0] == FIO:
        student[2] = new_group
    

In [280]:
mydict

{1: ['Иванов Иван', 18, 'A'],
 2: ['Петров Петр', 17, 'C'],
 3: ['Сидоров Андрей', 18, 'A']}

Добавьте к задаче No6 для словаря возможность (без преобразования словаря обратно в список) изменить возраст студента.

In [281]:
FIO = input('Введите ФИО: ')
new_age = input('Введите новый возраст: ')

for student in mydict.values():
    if student[0] == FIO:
        student[1] = new_age

Введите ФИО: Сидоров Андрей
Введите новый возраст: 16


In [283]:
mydict

{1: ['Иванов Иван', 18, 'A'],
 2: ['Петров Петр', 17, 'C'],
 3: ['Сидоров Андрей', '16', 'A']}